seed: 1

model:
  # pretrained_model_name_or_path: meta-llama/Llama-2-7b-chat-hf
  pretrained_model_name_or_path: TheBloke/Llama-2-7b-Chat-GPTQ
  # pretrained_model_name_or_path: cyberagent/open-calm-7b 
  device_map: auto
  torch_dtype: float32
  load_in_4bit: False
  load_in_8bit: False


generate:
  max_new_tokens: 100
  do_sample: True
  num_beams: 1
  num_return_sequences: 1
  remove_invalid_values: True

max_length: 100

dataset:
  data_path: /mnt/mint/karai/dataset/lima/test.jsonl
  datasize: 100
  batch_size: 4
  num_workers: 2
  padding: max_length

hydra:
  job:
    chdir: True
